### ISSUE TITLE
[sqlfiddle] EfCore fiddles appear to all be broken due to nuget issues?

### ISSUE THREAD

**Issue by npbenjohnson** [zzzprojects/fiddler-dev#13]
All of the examples for the entity framework extensions are broken. I tried fixing one up in [this example](https://dotnetfiddle.net/sUHFqd) by adding specific versions, which makes intellisense work correctly, but the server still returns errors as if the nuget packages aren't actually being imported.

**Comment by JonathanMagnan** [comment]
Hello @npbenjohnson ,

Thank you for reporting. It happens from time to time.

The docker VM has been restarted and everything look fine.

We will look to schedule an auto-restart every x hours. So the worse case scenario would be to be unavailable for 6h by example if we restart it every 6h.

Best Regards,

Jon

---
**Sponsorship**
[Help us improve this library](https://github.com/sponsors/zzzprojects)

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](https://entityframework-extensions.net/) • [Bulk Operations](https://bulk-operations.net/) •  [Dapper Plus](https://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](https://eval-expression.net/) • [SQL Eval Function](https://eval-sql.net/)
